# Generated by Django 5.0.2 on 2024-05-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('marca_modelo_auto', models.CharField(help_text='Describa la marca y modelo del auto.', max_length=100)),
                ('detalles', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=60)),
                ('numero_telef', models.PositiveIntegerField()),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('hora_salida', models.DateTimeField()),
                ('costo', models.FloatField()),
                ('estado', models.CharField(choices=[('espera', 'En espera'), ('lavando', 'En lavando'), ('terminado', 'Terminado')], default='espera', max_length=50)),
            ],
        ),
    ]
