# Generated by Django 5.0.2 on 2024-05-17 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_telef',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en el formato: '+529585552558'. Hasta 13 caracteres permitidos.", regex='^\\+?52?\\d{13,15}$')]),
        ),
    ]
