# Generated by Django 5.0.2 on 2024-05-17 08:05

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_alter_cliente_numero_telef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_telef',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
