# Generated by Django 5.0.2 on 2024-05-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_remove_cliente_hora_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='detalles',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('En espera', 'En espera'), ('En lavando', 'En lavando'), ('Terminado', 'Terminado')], default='En espera', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='matricula',
            field=models.CharField(max_length=7),
        ),
    ]
